export const initialState = [
  ["white", "white", "white", "white", "white"],
  [],
  [],
  [],
  ["black", "black", "black"],
  [],
  ["black", "black", "black", "black", "black"],
  [],
  [],
  [],
  [],
  ["white", "white"],
  ["black", "black", "black", "black", "black"],
  [],
  [],
  [],
  ["white", "white", "white"],
  [],
  ["white", "white", "white", "white", "white"],
  [],
  [],
  [],
  [],
  ["black", "black"],
];
